### ISSUE TITLE
Splunk Cloud: ImportError "No module named spurlib.api"

### ISSUE THREAD

**Issue by evan-chainalysis** [spurintel/spur-enrichment-for-splunk#1]
I've been attempting to deploy the App from SplunkBase into Splunk Cloud and running into an issue w/ Import pathing while attempting to run a basic query in Splunk Search. We're seeing the following error on execution of any search that calls the Spur Context API functions:

```
01-03-2024 18:35:55.705 INFO  ChunkedExternProcessor [2667500 searchOrchestrator] - Running process: /opt/splunk/bin/nsjail-wrapper /opt/splunk/bin/python2.7 /opt/splunk/etc/apps/spur-enrichment-for-splunk/bin/spurcontextapi.py
01-03-2024 18:35:55.840 ERROR ChunkedExternProcessor [2667508 ChunkedExternProcessorStderrLogger] - stderr: Traceback (most recent call last):
01-03-2024 18:35:55.840 ERROR ChunkedExternProcessor [2667508 ChunkedExternProcessorStderrLogger] - stderr:   File "/opt/splunk/etc/apps/spur-enrichment-for-splunk/bin/spurcontextapi.py", line 8, in <module>
01-03-2024 18:35:55.840 ERROR ChunkedExternProcessor [2667508 ChunkedExternProcessorStderrLogger] - stderr:     from spurlib.api import lookup
01-03-2024 18:35:55.840 ERROR ChunkedExternProcessor [2667508 ChunkedExternProcessorStderrLogger] - stderr: ImportError: No module named spurlib.api
```

For context the calling code that's erroring looks like this:
```py
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "splunklib"))
from splunklib.searchcommands import dispatch, StreamingCommand, Configuration, Option

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "spurlib"))
from spurlib.api import lookup
from spurlib.logging import setup_logging
from spurlib.secrets import get_encrypted_context_api_token
from spurlib.formatting import format_for_enrichment, ENRICHMENT_FIELDS
from spurlib.notify import notify_low_balance
from spurlib.conf import get_low_query_threshold
```

I suspect the issue is the inclusion of the `".."` in `os.path.join()`, after expansion the final path would be `./splunklib` instead of the actual path which is `./bin/splunklib/`. I can make a PR to issue a fix however I'm unable to test effectively due to limiting factors w/ Splunk Cloud private applications.

**Comment by jjunqueira** [comment]
Hi @evan-chainalysis,

Can you provide your splunk cloud version information? It looks like it is using python 2.7 which our app has not been tested against. We have tested it with the latest splunk cloud classic experience and it had no issues.

I did find an option for the configuration that will force the app to use python 3. I am going to add that option and submit the app again to see if that helps. 

Thank you!

**Comment by evan-chainalysis** [comment]
Splunk info:

```
## Splunk Cloud
Version: 9.0.2305.201
Build: 27efb34ea3c1
```

Awesome - I appreciate it! I've pushed a ticket w Splunk regarding their continued support for python2 🙃

**Comment by jjunqueira** [comment]
I added "python.version = python3" to the commands.conf in commit dda9e995ab25f56c8c61b18309ae20232c0ce60b. Version 1.0.3 has been uploaded to splunkbase but it is awaiting review for splunk cloud which can take a couple days. 

![image](https://github.com/spurintel/spur-enrichment-for-splunk/assets/7191655/52de6717-cb12-41c4-b200-2a47c688dbf1)

I currently only have access to a splunk classic instance for testing. The current version (1.0.2) is working fine on that version of splunk cloud. I'll post a comment here when the update is live.

![image](https://github.com/spurintel/spur-enrichment-for-splunk/assets/7191655/86bc0ee9-9526-4379-bb63-e0929f496ac2)

![image](https://github.com/spurintel/spur-enrichment-for-splunk/assets/7191655/468d77a0-492c-4e83-ae6e-5a78a2aa9f3a)

![image](https://github.com/spurintel/spur-enrichment-for-splunk/assets/7191655/2408ef7b-4ba4-4a6d-9bed-1c2f361ff1b6)

**Comment by evan-chainalysis** [comment]
Hey team! We can close this out with the most recent updates <3 thanks a bunch for triaging this so quickly!
